# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins:
  - jekyll-paginate-v2
  - jekyll-seo-tag

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: oracymartos
description: "Knowledge Sharing, Unix and others techs"
keywords: "Jekyll, Unix, linux, articles, SEO, blog, web"
url: http://oracymartos.online
baseurl: ""
google_analytics: UA-93790540-2
repo: https://github.com/Oracy/high
disqus_shortname: "oracymartos"
disqus_site_shortname: "oracymartos"

# Author settings
author:
  name: Oracy Martos
  job: DBA, backend developer
  bio: "Linux lover!! Enthusiast data, backend developer focused on server side!!! Always looking for the best project and good food."
  thumb: /images/author.jpg
  email: oramartos_21@hotmail.com
  url: http://oracymartos.online

# Twitter
twitter:
  username: Oracy_Martos
  card: summary

# Facebook
facebook:
  app_id: 2183221588472480

# TODO
# logo:

social:
  name: Oracy Martos
  links:
    - https://github.com/oracy
    - https://twitter.com/Oracy_Martos
    - https://facebook.com/OracyRezendeM
    - https://linkedin.com/in/oracymartos

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json", "README.md", "Rakefile"]
